name: quanlydiennc_app
description: "Quản lý hóa đơn điện nước cá nhân"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  http: ^1.0.0 
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  fl_chart: ^0.69.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  uuid: ^4.4.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
