// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTtyU1vIYppazT_Q2AN-BhmEUwDF8l44Y',
    appId: '1:1527546700:web:88353d5cf27881a2ebc5e9',
    messagingSenderId: '1527546700',
    projectId: 'roomzy-v2',
    authDomain: 'roomzy-v2.firebaseapp.com',
    storageBucket: 'roomzy-v2.firebasestorage.app',
    measurementId: 'G-F0Y1Y0W77C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa8TSQfqcfv_0tNZDMaj1wQWuf1WENngo',
    appId: '1:1527546700:android:e0fc9723225da961ebc5e9',
    messagingSenderId: '1527546700',
    projectId: 'roomzy-v2',
    storageBucket: 'roomzy-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1c-1TxRfMXI6qoOzuv-SAqPF1jhQPLpM',
    appId: '1:1527546700:ios:5cda99d30be0c45cebc5e9',
    messagingSenderId: '1527546700',
    projectId: 'roomzy-v2',
    storageBucket: 'roomzy-v2.firebasestorage.app',
    iosBundleId: 'com.example.quanlydienncApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1c-1TxRfMXI6qoOzuv-SAqPF1jhQPLpM',
    appId: '1:1527546700:ios:5cda99d30be0c45cebc5e9',
    messagingSenderId: '1527546700',
    projectId: 'roomzy-v2',
    storageBucket: 'roomzy-v2.firebasestorage.app',
    iosBundleId: 'com.example.quanlydienncApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTtyU1vIYppazT_Q2AN-BhmEUwDF8l44Y',
    appId: '1:1527546700:web:f9a1fd008e86fcacebc5e9',
    messagingSenderId: '1527546700',
    projectId: 'roomzy-v2',
    authDomain: 'roomzy-v2.firebaseapp.com',
    storageBucket: 'roomzy-v2.firebasestorage.app',
    measurementId: 'G-2WDM9M5VDE',
  );
}
